display_data: false

robot:
  type: so101_follower
  port: /dev/ttyACM0
  id: zarax
  cameras:
    camera_0:
      type: opencv
      index_or_path: /dev/video0
      fps: 30
      width: 640
      height: 480
    camera_1:
      type: opencv
      index_or_path: /dev/video2
      fps: 30
      width: 640
      height: 480

teleop:
  type: so101_leader
  port: /dev/ttyACM1
  id: zarax

dataset:
  repo_id: Zarax/zarax-demo-pi
  single_task: "Simple movement test"
  num_episodes: 3
  fps: 30
  push_to_hub: false
  video: true
